/* eslint-disable */

/**
 * This file is generated by chrome-i18n-code-gen, do not edit it
 */

export type Keys = "extName"|"extDescription"|"rulesTabName"|"settingsTabName"|"proxyStatusOn"|"proxyStatusOff"|"Theme"

export function i18n(key: Keys): string {
    return chrome.i18n.getMessage(key)
}